-- seatId alone was enough to call extend/order/end on any seat's session,
-- there are only 16 seats and the seat page takes the id straight from
-- the URL (?seat=N), so anyone could act on someone else's session just
-- by changing the number. Once a session has a saved card
-- (square_card_id), extend and order charge it with no re-entry of card
-- details, so this wasn't just "annoying", it meant a stranger could
-- trigger real charges on someone else's card.
--
-- access_token is populated three different ways depending on how the
-- session started:
--   - Solo guest sessions (seats/[id]/start.js, seats/[id]/redeem-held.js):
--     a random token generated the moment the session starts, returned
--     only to that guest's own browser.
--   - Group sessions (seats/group/start.js): one shared, short numeric
--     code for the whole group rather than a per-seat token, since the
--     group flow is designed so any member can order or extend from any
--     of the group's seats, from their own phone. Shown once on the
--     confirmation screen for the group to share, entered once per
--     device on first use (see seat.js's code prompt), then remembered
--     for every seat that device touches.
--   - Staff-started sessions (bookings/[id]/redeem-seat.js,
--     dashboard/claim-seat.js): no token at creation, there's no clean
--     way to hand one to the guest in that flow. Claimed instead by
--     whichever device is first to call extend/order on that session,
--     in practice the real guest's own first tap right after staff hand
--     the seat over.

ALTER TABLE sessions ADD COLUMN access_token TEXT;
