name = "digznlidz-session-expiry"
main = "session-expiry-cron.js"
compatibility_date = "2026-07-16"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "digznlidz-db"
database_id = "ed184220-8583-4633-9d47-ea653402f93e"

[vars]
EMAIL_FROM = "Digz N' Lidz <bookings@digznlidz.co.uk>"